#!/usr/bin/env perl

use uni::perl ':dumper';

use FindBin;
BEGIN { unshift @INC, "$FindBin::Bin/../lib" }

use iTunes::Today;
use Mojolicious::Plugin::Config;
use Mojo::mysql;
use Mojo::JSON qw( encode_json );
use DateTime;

my ( $confpath, $start_date, $end_date ) = @ARGV;
my $config = Mojolicious::Plugin::Config->load($confpath);

#say dumper { config => $config };

my $mysql =
  Mojo::mysql->strict_mode( 'mysql://'
      . $config->{db}{user} . ':'
      . $config->{db}{pass} . '@'
      . $config->{db}{host} . '/'
      . $config->{db}{name} );

$start_date ||= DateTime->now->ymd;
$end_date   ||= $start_date;

say dumper [ $start_date, $end_date ];

my $parser = iTunes::Today->new( $config->{itunes_today} );

for my $country ( @{ $config->{countries} } ) {
    my $result = $parser->parse(
        country    => $country,
        start_date => $start_date,
        end_date   => $end_date
    );

    #say dumper $result;

    foreach my $story ( @{ $result->{res_json}[0]{stories} } ) {
        next
          if $mysql->db->query( 'select count(1) as "exists" from stories where id = ?', $story->{id} )
          ->hash->{exists};

        say 'inserting';
        my $json_source = encode_json($story);
        say dumper $story;
        say dumper $json_source;

        eval {
            $mysql->db->query(
                'insert into stories (id,label,date,country,json_source) values (?,?,?,?,?)',
                $story->{id},
                $story->{label},
                [ split( 'T', $result->{res_json}[0]{date} ) ]->[0],
                $result->{res_json}[0]{country},
                $json_source
            );
        };

        warn $@ if $@;
    }
}

1;
